name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Esegui il deploy solo quando c'è una commit sulla branch principale (puoi cambiare la branch se necessario)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Daily-Inspire

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Specifica la versione di Node.js richiesta dal tuo progetto

    - name: Generate environment.ts
      run: |
            mkdir -p src/environments
            echo "export const environment = {" > src/environments/environment.ts
            echo "  production: true," >> src/environments/environment.ts
            echo "  firebaseConfig: {" >> src/environments/environment.ts
            echo "    apiKey: '${{ secrets.APIKEY }}'," >> src/environments/environment.ts
            echo "    authDomain: '${{ secrets.AUTHDOMAIN }}'," >> src/environments/environment.ts
            echo "    databaseURL: '${{ secrets.DATABASEURL }}'," >> src/environments/environment.ts
            echo "    projectId: '${{ secrets.PROJECTID }}'," >> src/environments/environment.ts
            echo "    storageBucket: '${{ secrets.STORAGEBUCKET }}'," >> src/environments/environment.ts
            echo "    messagingSenderId: '${{ secrets.MESSAGINGSENDERID }}'," >> src/environments/environment.ts
            echo "    appId: '${{ secrets.APPID }}'," >> src/environments/environment.ts
            echo "    measurementId: '${{ secrets.MEASUREMENTID }}'," >> src/environments/environment.ts
            echo "  }," >> src/environments/environment.ts
            echo " emailJS_ServiceID: '${{ secrets.EMAILJS_SERVICE_ID }}'," >> src/environments/environment.ts
            echo " emailJS_TemplateID: '${{ secrets.EMAILJS_TEMPLATE_ID }}'," >> src/environments/environment.ts
            echo " emailJS_UserID: '${{ secrets.EMAILJS_USER_ID }}'" >> src/environments/environment.ts
            echo "};" >> src/environments/environment.ts

    - name: Generate environment.prod.ts
      run: |
          mkdir -p src/environments
          echo "export const environment = {" > src/environments/environment.prod.ts
          echo "  production: true," >> src/environments/environment.prod.ts
          echo "  firebaseConfig: {" >> src/environments/environment.prod.ts
          echo "    apiKey: '${{ secrets.APIKEY }}'," >> src/environments/environment.prod.ts
          echo "    authDomain: '${{ secrets.AUTHDOMAIN }}'," >> src/environments/environment.prod.ts
          echo "    databaseURL: '${{ secrets.DATABASEURL }}'," >> src/environments/environment.prod.ts
          echo "    projectId: '${{ secrets.PROJECTID }}'," >> src/environments/environment.prod.ts
          echo "    storageBucket: '${{ secrets.STORAGEBUCKET }}'," >> src/environments/environment.prod.ts
          echo "    messagingSenderId: '${{ secrets.MESSAGINGSENDERID }}'," >> src/environments/environment.prod.ts
          echo "    appId: '${{ secrets.APPID }}'," >> src/environments/environment.prod.ts
          echo "    measurementId: '${{ secrets.MEASUREMENTID }}'," >> src/environments/environment.prod.ts
          echo "  }," >> src/environments/environment.prod.ts
          echo " emailJS_ServiceID: '${{ secrets.EMAILJS_SERVICE_ID }}'," >> src/environments/environment.prod.ts
          echo " emailJS_TemplateID: '${{ secrets.EMAILJS_TEMPLATE_ID }}'," >> src/environments/environment.prod.ts
          echo " emailJS_UserID: '${{ secrets.EMAILJS_USER_ID }}'" >> src/environments/environment.prod.ts
          echo "};" >> src/environments/environment.prod.ts

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build Angular app
      run: npm run build --prod

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DAILYINSPIRE_41B75 }}
      run: |
        npm install -g firebase-tools
        firebase deploy --only hosting --project dailyinspire-41b75
    
    - name: Salva environment.prod.ts come artefatto
      uses: actions/upload-artifact@v3.1.0
      with:
        name: environment-prod
        path: src/environments/environment.prod.ts
